### ISSUE TITLE
Parser is used when Generator makes more sense?

### ISSUE THREAD

**Issue by dougreichard** [matteckert/gulp-jison#2]
The Plugin uses the parser instead of a Generator.

```
require('jison').Parser;
```

Should be

```
 require('jison').Generator;
```

The reason is that if you use the Parser the a Parser is created when it is not even needed. When you have embedded code in the jison file that code is execute. The code generated runs fine when I changed to use the generator.

**Comment by matteckert** [comment]
The suggested code change fails tests.

**Comment by dougreichard** [comment]
Thanks for the quick look at the issue I submitted.

I'll try to create a simple example so you can see the problem I'm seeing.  You can ignore it, or address the issue. Your plugin is useful and we wouldn't want another one just to work around this issue, but there is an issue that can be fixed.

Maybe an example of the problem I'm seeing will help. Using your test add a dependencies for example:

```
. . .
/lex 

%{
var ast = require('./calcfuncs.js')
%}

. . .
```

Using a generator the file is created and its fine. Using the Parser it cannot find the dependency and fails.  jison does an eval() with 'Parser' and that is where it fails to find the dependent file. Its unclear to me if the cwd has changed or what, but it fails to load the calcfuncs.js file. calcfuncs.js is in the same directory as my jison and the generated .js file.

In reality, my parser is using an AST and lots of code related to that is in the jison file.

I'm assuming you want the myparser.js file generated like I do. Your test uses the Parser to validate success, maybe if it used the generated file, it would pass with the Generator. Or maybe its a cwd problem. jison works with the generator I get what I want. If you'd like me to fork and update the test myself let me know I'll give it a go.

**Comment by matteckert** [comment]
Thank you for the explanation. Reopened and working on an update.

**Comment by dougreichard** [comment]
Thanks. Works great.
